spring:
  config:
    import:
      - mysql.yml
      - s3.yml
  application:
    name: zerowaste
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    root: info
server:
  port: 0

---
spring.config.activate.on-profile: local

spring:
  config:
    import:
      - optional:classpath:env.properties

---
spring.config.activate.on-profile: dev