spring:
  config:
    import:
      - mysql.yml
  application:
    name: zerowaste

logging:
  level:
    root: info
server:
  port: 8080

---
spring.config.activate.on-profile: local

---
spring.config.activate.on-profile: dev