name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Extract short SHA
        id: vars
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Print SHA value
        run: echo "Short SHA is ${{ steps.vars.outputs.sha }}"

      - name: Download SHA artifact
        uses: actions/download-artifact@v4
        with:
          name: image-sha

      - name: Read image tag from artifact
        id: sha
        run: echo "sha=$(cat image-sha.txt)" >> $GITHUB_OUTPUT

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        env:
          IMAGE_NAME: ${{ secrets.SPRING_IMAGE }}
          MYSQL_URL: ${{ secrets.MYSQL_URL }}
          MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            IMAGE_TAG="${IMAGE_NAME}:${{ steps.sha.outputs.sha }}"
            IMAGE_TAG=$(echo "$IMAGE_TAG" | xargs)

            echo "Deploying image: $IMAGE_TAG"

            # 실행 중인 컨테이너 있으면 중지
            if sudo docker ps -q -f name=zerowaste-server | grep -q .; then
              sudo docker stop zerowaste-server
            fi

            # 존재하는 컨테이너 있으면 삭제
            if sudo docker ps -a -q -f name=zerowaste-server | grep -q .; then
              sudo docker rm zerowaste-server
            fi

            sudo docker pull "$IMAGE_TAG"

            sudo docker run -d \
              --name zerowaste-server \
              -p 8080:8080 \
              -e MYSQL_URL="${MYSQL_URL}" \
              -e MYSQL_USERNAME="${MYSQL_USERNAME}" \
              -e MYSQL_PASSWORD="${MYSQL_PASSWORD}" \
              "$IMAGE_TAG"
